### ISSUE TITLE
[MALWARE]DO NOT DOWNLOAD

### ISSUE THREAD

**Issue by paddy41601** [yaelahrip/hwidpcspoofer#1]
[MALWARE]DO NOT DOWNLOAD
[MALWARE]DO NOT DOWNLOAD
[MALWARE]DO NOT DOWNLOAD
[MALWARE]DO NOT DOWNLOAD
[MALWARE]DO NOT DOWNLOAD

**Comment by yaelahrip** [comment]
protected with Themida. i dunno. my code is clean lol
